package com.volpi.api.model.enums;

public enum GradeEnum {
    FUNDAMENTAL_1_ANO,
    FUNDAMENTAL_2_ANO,
    FUNDAMENTAL_3_ANO,
    FUNDAMENTAL_4_ANO,
    FUNDAMENTAL_5_ANO,
    FUNDAMENTAL_6_ANO,
    FUNDAMENTAL_7_ANO,
    FUNDAMENTAL_8_ANO,
    FUNDAMENTAL_9_ANO,
    ENSINO_MEDIO_1_SERIE,
    ENSINO_MEDIO_2_SERIE,
    ENSINO_MEDIO_3_SERIE
}

